permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
baseurl: ""



title: "InfoRekt; constructive feedback on infosec fails"
email: "captainhindsight@inforekt.fail"
description: "Got Rekt? Probably an OpSec fail."
github_username:  "InfoRekt"
excerpt_separator: "\n\n"

url: "https://inforekt.fail"
