permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
baseurl: ""



title: "InfoRekt; constructive feedback on infosec fails"
email: "captainhindsight@inforekt.fail"
description: "Got Rekt? Probably an OpSec fail."
github_username:  "InfoRekt"

#url: "http://127.0.0.1:4000"
url: "https://inforekt.github.io"

